#!/bin/bash

implemented=true
blank=false
url=""
deps=""
description=""
version="latest"

instal_algo()
{
	 echo "Here should be actual installation logic"
}

remove_algo()
{
	echo "Here should be actual removal logic"
}
